packages:
  - "apps/*"
  - "benchmarks/*"
  - "packages/*"
allowBuilds:
  '@google/genai': true
  "@parcel/watcher": true
  openclaw: true
  protobufjs: true
  tree-sitter-bash: true
  vue-demi: true
