"""Decision models and merge logic for AgentGuard Core."""

from .models import (
    ApprovalIntent,
    ApprovalResolution,
    AuditEvent,
    AuditRecordType,
    Decision,
    GuardDecision,
    RuntimeBindingCheckStatus,
    RuntimeEnforcementEvidence,
    RuntimeEnforcementGateState,
    RuntimeEnforcementReasonCode,
    RuntimeLeaseConsumeOutcome,
    RuntimeOutcomeReceipt,
    RuleHit,
    RuleOverrideDecision,
)
from .runtime_observations import (
    PreEvaluationBlockDiagnostic,
    PreEvaluationBlockFailureCode,
)
from .policy import build_guard_decision
from .results import DetectionResult

__all__ = [
    "ApprovalIntent",
    "ActivationAckV1",
    "ApprovalReleaseDirectiveV2",
    "ApprovalResolution",
    "AuditEvent",
    "AuditRecordType",
    "Decision",
    "DetectionResult",
    "FusionBehaviorRule",
    "FusionFlowRule",
    "FusionInfluenceRule",
    "FusionMatrix",
    "FusionMatrixError",
    "FusionMemoryRule",
    "FastAssessment",
    "GuardDecision",
    "CompetitionActivationManifestV1",
    "ProductActivationBundleV1",
    "OpenClawFrozenToolV1",
    "OpenClawInventoryDigestsV1",
    "OPENCLAW_RESIDUAL_BOUNDARIES",
    "ProductDecisionAuthorityEvidenceV1",
    "PreEvaluationBlockDiagnostic",
    "PreEvaluationBlockFailureCode",
    "ResidualRiskAcceptanceV1",
    "RolloutAdmissionRecordV1",
    "RuntimeActivationEntryV1",
    "RuntimeCapabilityReportV2",
    "RuntimeEventCapabilityV2",
    "ApprovalRelease",
    "DecisionAuthority",
    "DecisionAuthorityEvidenceV1",
    "DecisionSource",
    "EnabledV21PathId",
    "SelectionBasis",
    "V21AuthoritySelectionError",
    "V21Mode",
    "V21SelectionEligibility",
    "V21SelectionResult",
    "RuntimeBindingCheckStatus",
    "RuntimeEnforcementEvidence",
    "RuntimeEnforcementGateState",
    "RuntimeEnforcementReasonCode",
    "RuntimeLeaseConsumeOutcome",
    "RuntimeOutcomeReceipt",
    "RuleHit",
    "RuleOverrideDecision",
    "build_guard_decision",
    "dedupe_evidence_groups",
    "evaluate_fusion",
    "load_fusion_matrix",
    "build_competition_activation_manifest",
    "build_activation_ack",
    "build_approval_release_directive",
    "build_product_activation_bundle",
    "build_openclaw_inventory_digests",
    "build_product_decision_authority_evidence",
    "build_residual_risk_acceptance",
    "build_rollout_admission_record",
    "build_runtime_capability_report",
    "build_decision_authority_evidence",
    "build_v21_official_decision",
    "decision_authority_envelope",
    "match_limited_paths",
    "select_v21_authority",
    "legacy_approval_release_projection",
    "openclaw_tool_event_type",
    "openclaw_event_residual_boundaries",
    "product_decision_authority_envelope",
    "select_product_v21_authority",
    "verify_activation_ack",
    "verify_activation_ack_token",
    "verify_competition_activation_manifest",
    "verify_product_activation_bundle",
    "verify_residual_risk_acceptance",
    "verify_rollout_admission_record",
]

# V21-08 fusion 求值器（纯新增导出）。必须放在本文件末尾：fusion 依赖
# ``security_context``，而 ``security_context.snapshot`` 反向导入
# ``decisions.evidence``——先完成上述既有导出，保证环上的
# ``decisions.models``/``decisions.evidence`` 已就绪，避免部分初始化环。
from .fusion import (  # noqa: E402
    FusionBehaviorRule,
    FusionFlowRule,
    FusionInfluenceRule,
    FusionMatrix,
    FusionMatrixError,
    FusionMemoryRule,
    dedupe_evidence_groups,
    evaluate_fusion,
    load_fusion_matrix,
)
from .evidence import FastAssessment  # noqa: E402
from .competition import (  # noqa: E402
    ApprovalRelease,
    CompetitionActivationManifestV1,
    DecisionAuthority,
    DecisionAuthorityEvidenceV1,
    DecisionSource,
    EnabledV21PathId,
    SelectionBasis,
    V21AuthoritySelectionError,
    V21Mode,
    V21SelectionEligibility,
    V21SelectionResult,
    build_competition_activation_manifest,
    build_decision_authority_evidence,
    build_v21_official_decision,
    decision_authority_envelope,
    match_limited_paths,
    select_v21_authority,
    verify_competition_activation_manifest,
)
from .product import (  # noqa: E402
    ActivationAckV1,
    ApprovalReleaseDirectiveV2,
    OPENCLAW_RESIDUAL_BOUNDARIES,
    ProductActivationBundleV1,
    OpenClawFrozenToolV1,
    OpenClawInventoryDigestsV1,
    ProductDecisionAuthorityEvidenceV1,
    ResidualRiskAcceptanceV1,
    RolloutAdmissionRecordV1,
    RuntimeActivationEntryV1,
    RuntimeCapabilityReportV2,
    RuntimeEventCapabilityV2,
    build_activation_ack,
    build_approval_release_directive,
    build_product_activation_bundle,
    build_openclaw_inventory_digests,
    build_product_decision_authority_evidence,
    build_residual_risk_acceptance,
    build_rollout_admission_record,
    build_runtime_capability_report,
    legacy_approval_release_projection,
    openclaw_event_residual_boundaries,
    openclaw_tool_event_type,
    product_decision_authority_envelope,
    select_product_v21_authority,
    verify_activation_ack,
    verify_activation_ack_token,
    verify_product_activation_bundle,
    verify_residual_risk_acceptance,
    verify_rollout_admission_record,
)
